version: "3.9"
services:
  redis:
    image: redis:7.0.8-alpine
    container_name: 'redis'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file: .env
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env
    depends_on:
      - redis
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    env_file: .env
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mongodb
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
      - redis
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./api:/api
    env_file: .env
  extractor:
    build:
      context: .
      dockerfile: ./extractor/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./extractor:/extractor
    env_file: .env
  flashcard_model:
    build:
      context: .
      dockerfile: ./flashcard_model/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./flashcard_model:/flashcard_model
    env_file: .env