CHAT_GPT_MODEL_KEY = "CHAT_GPT"
DEMO_MODEL_KEY = "DEMO"
T5_MODEL_KEY = "T5"
VIT_GPT2_MODEL_KEY = "VIT_GPT2"
MODEL_KEYS = [CHAT_GPT_MODEL_KEY, DEMO_MODEL_KEY, T5_MODEL_KEY, VIT_GPT2_MODEL_KEY]

TORCH_DEVICE = "cpu"
T5_HUGGINGFACE_MODEL_NAME = "prnv13/flan-t5-base-gold"
